# Generated by Django 4.0.3 on 2022-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
