# Generated by Django 4.0.3 on 2022-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
